/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sorting;
import java.util.*;
public class App {
  
    public static void main(String[] args) {
    
        int[] toSort = new int[]{5,2,1,9,7,22,1};
       
        insertionSort(toSort);
    }
    
    /*
    insertionSort, takes O(n^2) as time complexity, convenient for smaller arrays, but is inefficient as size of
    */
    public static void insertionSort(int[] toSort){

        for(int j = 1; j < toSort.length; j++){
            int key = toSort[j];
            int i = j - 1;

            while(i > -1 && toSort[i] > key){
                toSort[i + 1] = toSort[i];
                i--;
            }
            toSort[++i] = key;
        }

        for (int var : toSort) {
            System.out.println(var);
        }
    }

    // public static void selectionSort(){

    // }
    
    // public static void mergeSort(){
        
    // }

    // public static void quickSort(){

    // }
}
