/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package recursion;

public class App {
    // public String getGreeting() {
    //     return "Hello world.";
    // }

    public static int fib(int n){
        
        if(n > 2){
            return fib(n - 1) + fib(n - 2);
        }
        else{
            return 1;
        }
    }

    public static void main(String[] args) {
        int test = 6;
        int answer;

        answer = fib(test);
        System.out.println(answer);

    }
}
